export const product = [
  {
    id: "000001",
    code: "P22030297",
    name: "CALIBURN AK2 (Black) เครื่องสีดำ",
    group: "CALIBURN AK2",
    type: "เครื่องแบบหัวเติมน้ำยา",
    brand: "CALIBURN",
    amount: 0,
    unit: "psc",
    cost_price: 600,
    price: 990,
  },
  {
    id: "000002",
    code: "P22030307",
    name: "คอยล์ COIL CALIBURN 0.9 โอม ( A2 , AK2 )",
    group: "คอยล์ COIL CALIBURN 0.9 โอม ( A2 , AK2 )",
    type: "หัวคอยล์",
    brand: "CALIBURN",
    amount: 1,
    unit: "psc",
    cost_price: 320,
    price: 500,
  },
  {
    id: "000003",
    code: "P22030390",
    name: "น้ำยา องุ่น MARBO สั้น 30ML 35% สีม่วง",
    group: "น้ำยา marbo สั่น",
    type: "น้ำยาขวด",
    brand: "MARBO",
    amount: "82",
    unit: "psc",
    cost_price: 155,
    price: 250,
  },
];
